# Generated by Django 5.0.4 on 2024-10-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_productonhold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
